In [ ]:
!pip install snowflake-connector-python

Requirement already satisfied: snowflake-connector-python in /usr/local/lib/python3.12/dist-packages (4.5.0)
Requirement already satisfied: asn1crypto<2.0.0,>0.24.0 in /usr/local/lib/python3.12/dist-packages (from snowflake-connector-python) (1.5.1)
Requirement already satisfied: cryptography>=46.0.5 in /usr/local/lib/python3.12/dist-packages (from snowflake-connector-python) (48.0.0)
Requirement already satisfied: pyOpenSSL>=24.0.0 in /usr/local/lib/python3.12/dist-packages (from snowflake-connector-python) (26.2.0)
Requirement already satisfied: pyjwt<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from snowflake-connector-python) (2.12.1)
Requirement already satisfied: pytz in /usr/local/lib/python3.12/dist-packages (from snowflake-connector-python) (2025.2)
Requirement already satisfied: requests<3.0.0,>=2.32.4 in /usr/local/lib/python3.12/dist-packages (from snowflake-connector-python) (2.32.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from snowflake-connector-python) (26.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from snowflake-connector-python) (3.4.7)
Requirement already satisfied: idna<4,>=3.7 in /usr/local/lib/python3.12/dist-packages (from snowflake-connector-python) (3.13)
Requirement already satisfied: certifi>=2024.7.4 in /usr/local/lib/python3.12/dist-packages (from snowflake-connector-python) (2026.4.22)
Requirement already satisfied: typing_extensions<5,>=4.3 in /usr/local/lib/python3.12/dist-packages (from snowflake-connector-python) (4.15.0)
Requirement already satisfied: filelock<4,>=3.5 in /usr/local/lib/python3.12/dist-packages (from snowflake-connector-python) (3.29.0)
Requirement already satisfied: sortedcontainers>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from snowflake-connector-python) (2.4.0)
Requirement already satisfied: platformdirs<5.0.0,>=2.6.0 in /usr/local/lib/python3.12/dist-packages (from snowflake-connector-python) (4.9.6)
Requirement already satisfied: tomlkit in /usr/local/lib/python3.12/dist-packages (from snowflake-connector-python) (0.13.3)
Requirement already satisfied: boto3>=1.24 in /usr/local/lib/python3.12/dist-packages (from snowflake-connector-python) (1.43.14)
Requirement already satisfied: botocore>=1.24 in /usr/local/lib/python3.12/dist-packages (from snowflake-connector-python) (1.43.14)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from boto3>=1.24->snowflake-connector-python) (1.1.0)
Requirement already satisfied: s3transfer<0.18.0,>=0.17.0 in /usr/local/lib/python3.12/dist-packages (from boto3>=1.24->snowflake-connector-python) (0.17.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.12/dist-packages (from botocore>=1.24->snowflake-connector-python) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.12/dist-packages (from botocore>=1.24->snowflake-connector-python) (2.5.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography>=46.0.5->snowflake-connector-python) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography>=46.0.5->snowflake-connector-python) (3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore>=1.24->snowflake-connector-python) (1.17.0)

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
import  snowflake.connector
con=snowflake.connector.connect(
    user='adhidhya',
    password='Adhidhya_31428',
    account='KQUUHOO-UP24252',
    database='water',
    schema='PUBLIC',
    warehouse='COMPUTE_WH'

)

In [ ]:
df=pd.read_sql('select * from SVM',con)

/tmp/ipykernel_398/3666047610.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql('select * from SVM',con)

In [ ]:
con.close()

In [ ]:
df

            PH    HARDNESS  ...  TURBIDITY  POTABILITY
0          NaN  204.890455  ...   2.963135           0
1     3.716080  129.422921  ...   4.500656           0
2     8.099124  224.236259  ...   3.055934           0
3     8.316766  214.373394  ...   4.628771           0
4     9.092223  181.101509  ...   4.075075           0
...        ...         ...  ...        ...         ...
3271  4.668102  193.681735  ...   4.435821           1
3272  7.808856  193.553212  ...   2.798243           1
3273  9.419510  175.762646  ...   3.298875           1
3274  5.126763  230.603758  ...   4.708658           1
3275  7.874671  195.102299  ...   2.309149           1

[3276 rows x 10 columns]

In [ ]:
df.shape

(3276, 10)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3276 entries, 0 to 3275
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PH               2785 non-null   float64
 1   HARDNESS         3276 non-null   float64
 2   SOLIDS           3276 non-null   float64
 3   CHLORAMINES      3276 non-null   float64
 4   SULFATE          2495 non-null   float64
 5   CONDUCTIVITY     3276 non-null   float64
 6   ORGANIC_CARBON   3276 non-null   float64
 7   TRIHALOMETHANES  3114 non-null   float64
 8   TURBIDITY        3276 non-null   float64
 9   POTABILITY       3276 non-null   int64
dtypes: float64(9), int64(1)
memory usage: 256.1 KB

In [ ]:
df.describe()

                PH     HARDNESS  ...    TURBIDITY   POTABILITY
count  2785.000000  3276.000000  ...  3276.000000  3276.000000
mean      7.080795   196.369496  ...     3.966786     0.390110
std       1.594320    32.879761  ...     0.780382     0.487849
min       0.000000    47.432000  ...     1.450000     0.000000
25%       6.093092   176.850538  ...     3.439711     0.000000
50%       7.036752   196.967627  ...     3.955028     0.000000
75%       8.062066   216.667456  ...     4.500320     1.000000
max      14.000000   323.124000  ...     6.739000     1.000000

[8 rows x 10 columns]

In [ ]:
df.isnull().sum()

PH                 491
HARDNESS             0
SOLIDS               0
CHLORAMINES          0
SULFATE            781
CONDUCTIVITY         0
ORGANIC_CARBON       0
TRIHALOMETHANES    162
TURBIDITY            0
POTABILITY           0
dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='median')

df[df.columns] = imputer.fit_transform(df)

In [ ]:
numeric_cols = df.select_dtypes(include=np.number).columns.tolist()

for col in numeric_cols:
  q1=df[col].quantile(0.25)
  q3=df[col].quantile(0.75)
  iqr=q3-q1
  lower=q1-1.5*iqr
  upper=q3+1.5*iqr
  df[col]=df[col].clip(lower,upper)

In [ ]:
df

            PH    HARDNESS  ...  TURBIDITY  POTABILITY
0     7.080795  204.890455  ...   2.963135           0
1     3.889107  129.422921  ...   4.500656           0
2     8.099124  224.236259  ...   3.055934           0
3     8.316766  214.373394  ...   4.628771           0
4     9.092223  181.101509  ...   4.075075           0
...        ...         ...  ...        ...         ...
3271  4.668102  193.681735  ...   4.435821           1
3272  7.808856  193.553212  ...   2.798243           1
3273  9.419510  175.762646  ...   3.298875           1
3274  5.126763  230.603758  ...   4.708658           1
3275  7.874671  195.102299  ...   2.309149           1

[3276 rows x 10 columns]

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
svm_model=SVC()
x=df.drop(['POTABILITY'],axis=1)
y=df['POTABILITY']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=42)

In [ ]:
svm_model.fit(x_train,y_train)

SVC()

In [ ]:
y_pred=svm_model.predict(x_test)

In [ ]:
print(accuracy_score(y_pred,y_test))

0.623951182303585